import { ObjectId } from 'mongodb';
import { Schema, model } from 'mongoose';
import { IBaseModel } from './base-model';

export interface IDanhSachTrungTuyen extends IBaseModel {
    idDotNhapHoc: String,
    maNhapHoc: String,
    maHoSo?: String,
    quocTich: String,
    danToc?: String,
    ho: String,
    ten: String,
    ngaySinh: Date,
    gioiTinh: String,
    cmnd?: String,
    sdt?: String,
    idTinh?: String,
    idHuyen?: String,
    idXa?: String,
    email?: String,
    idNganhDangKy: String,
    idNganhTrungTuyen: String,
    diemMon1?: Number,
    diemMon2?: Number,
    diemMon3?: Number,
    diemCong?: Number,
    tongDiem?: Number,
    toHopMon?: String,
    khuVuc?: String,
    soBaoDanh?: String,
    idHtTuyenSinh: String,
    idDoiTuongTuyenSinh: String,
    idDoiTuongUuTien?: String,
    idDoiTuongDaoTao: String,
    ghiChu?: String,
    ngayQdTrungTuyen?: Date,
    timeNhapHoc?: Date,
    diaDiemNhapHoc?: String,
    maTinhLop12?: String,
    maTruongLop12?: String,
    thuTuNv?: Number,
    hocLucTHPT?: String,
    hanhKiemTHPT?: String,
    diaChiNhanGiayBao?: String,
    soQD?: String,
    ngayImport?: Date,
    maSV: String,
    trangThai: String
}

const schema = new Schema<IDanhSachTrungTuyen>({
    _id: ObjectId,
    idDotNhapHoc: { type: String, required: true },
    maNhapHoc: { type: String, required: true },
    maHoSo: { type: String, required: false },
    quocTich: { type: String, required: true },
    danToc: { type: String, required: false },
    ho: { type: String, required: true },
    ten: { type: String, required: true },
    ngaySinh: { type: Date, required: true },
    gioiTinh: { type: String, required: true },
    cmnd: { type: String, required: false },
    sdt: { type: String, required: false },
    idTinh: { type: String, required: false },
    idHuyen: { type: String, required: false },
    idXa: { type: String, required: false },
    email: { type: String, required: true },
    idNganhDangKy: { type: String, required: true },
    idNganhTrungTuyen: { type: String, required: true },
    diemMon1: { type: String, required: false },
    diemMon2: { type: Number, required: false },
    diemMon3: { type: Number, required: false },
    diemCong: { type: Number, required: false },
    tongDiem: { type: Number, required: false },
    toHopMon: { type: String, required: false },
    khuVuc: { type: String, required: false },
    soBaoDanh: { type: String, required: false },
    idHtTuyenSinh: { type: String, required: false },
    idDoiTuongTuyenSinh: { type: String, required: true },
    idDoiTuongUuTien: { type: String, required: false },
    idDoiTuongDaoTao: { type: String, required: true },
    ghiChu: { type: String, required: false },
    ngayQdTrungTuyen: { type: Date, required: false },
    timeNhapHoc: { type: Date, required: false },
    diaDiemNhapHoc: { type: String, required: false },
    maTinhLop12: { type: String, required: false },
    maTruongLop12: { type: String, required: false },
    thuTuNv: { type: Number, required: false },
    hocLucTHPT: { type: String, required: false },
    hanhKiemTHPT: { type: String, required: false },
    diaChiNhanGiayBao: { type: String, required: false },
    soQD: { type: String, required: false },
    ngayImport: { type: Date, required: false },
    maSV: { type: String, required: true },
    trangThai: { type: String, required: true }
});

export default model<IDanhSachTrungTuyen>('DanhSachTrungTuyen', schema);
