import { ObjectId } from 'mongodb';
import { Schema, model } from 'mongoose';
import { IBaseModel } from './base-model';

export interface IHoSoNguoiHoc extends IBaseModel {
    masv: String,
    Ho: String,
    Ten: String,
    hoVaTen: String,
    GioiTinh: String,
    idDanToc: String,
    idTonGiao: String,
    idQuocTich: String,
    CmndSo: String,
    CmndNgayCap: Date,
    CmndNoiCap: String,
    Anh: String,
    GhiChu: String,
    NhapHocNamHoc: String,
    NoiTru: String,
    DiaChiLienLac: String,
    DienThoai: String,
    Email: String,
    idLopHanhChinh: String,
    idHe: String,
    idKhoa: String,
    idKhoaHoc: String,
    idNganh: String,
    idTrangThai: String,
    idLopHienTai: String,
    idKhoaVien: String,
    idChuyenNganh: String,
    QueQuanDiaChi: String,
    NgaySinh: Date,
    idDoiTuongDaoTao: String,
    NgayQuyetDinhThoiHoc: Date,
}

const schema = new Schema<IHoSoNguoiHoc>({
    _id: ObjectId,
    masv: { type: String, required: true },
    Ho: { type: String, required: true },
    Ten: { type: String, required: true },
    hoVaTen: { type: String, required: false },
    GioiTinh: { type: String, required: false },
    idDanToc: { type: String, required: false },
    idTonGiao: { type: String, required: false },
    idQuocTich: { type: String, required: false },
    CmndSo: { type: String, required: false },
    CmndNgayCap: { type: Date, required: false },
    CmndNoiCap: { type: String, required: false },
    Anh: { type: String, required: false },
    GhiChu: { type: String, required: false },
    NhapHocNamHoc: { type: String, required: false },
    NoiTru: { type: String, required: false },
    DiaChiLienLac: { type: String, required: false },
    DienThoai: { type: String, required: false },
    Email: { type: String, required: false },
    idLopHanhChinh: { type: String, required: true },
    idHe: { type: String, required: true },
    idKhoa: { type: String, required: true },
    idKhoaHoc: { type: String, required: true },
    idNganh: { type: String, required: true },
    idTrangThai: { type: String, required: true },
    idLopHienTai: { type: String, required: false },
    idKhoaVien: { type: String, required: false },
    idChuyenNganh: { type: String, required: false },
    QueQuanDiaChi: { type: String, required: false },
    NgaySinh: { type: Date, required: true },
    idDoiTuongDaoTao: { type: String, required: false },
    NgayQuyetDinhThoiHoc: { type: Date, required: false },
});

export default model<IHoSoNguoiHoc>('HoSoNguoiHoc', schema);
