import { ObjectId } from 'mongodb';
import { Schema, model } from 'mongoose';
import { IBaseModel } from './base-model';

export interface IHoSoNguoiHoc extends IBaseModel {
    maSv: String,
    ho: String,
    ten: String,
    hoVaTen: String,
    gioiTinh: String,
    idDanToc: String,
    idTonGiao: String,
    idQuocTich: String,
    cmndSo: String,
    cmndNgayCap: Date,
    cmndNoiCap: String,
    anh: String,
    nhapHocNamHoc: String,
    noiTru: String,
    idTinhqq: String,
    idHuyenqq: String,
    idXaqq: String,
    idTinhtt: String,
    idHuyentt: String,
    idXatt: String,
    idTinhhn: String,
    idHuyenhn: String,
    idXahn: String,
    dienThoai: String,
    email: String,
    idLopHanhChinh: String,
    idHe: String,
    idKhoa: String,
    idKhoaHoc: String,
    idNganh: String,
    idTrangThai: String,
    idLopHienTai: String,
    idKhoaVien: String,
    moiQuanHe: String,
    tenNhanThan: String,
    ngaySinhNhanThan: String,
    ngheNghiepNhanThan: String,
    noiONhanThan: String,
    sdtNhanThan: String,
    ngaySinh: Date,
    idDoiTuongDaoTao: String,
    ngayQuyetDinhThoiHoc: Date,
}

const schema = new Schema<IHoSoNguoiHoc>({
    _id: ObjectId,
    maSv: { type: String, required: true },
    ho: { type: String, required: true },
    ten: { type: String, required: true },
    hoVaTen: { type: String, required: false },
    gioiTinh: { type: String, required: false },
    idDanToc: { type: String, required: false },
    idTonGiao: { type: String, required: false },
    idQuocTich: { type: String, required: false },
    cmndSo: { type: String, required: false },
    cmndNgayCap: { type: Date, required: false },
    cmndNoiCap: { type: String, required: false },
    anh: { type: String, required: false },
    nhapHocNamHoc: { type: String, required: false },
    noiTru: { type: String, required: false },
    idTinhqq: { type: String, required: false },
    idHuyenqq: { type: String, required: false },
    idXaqq: { type: String, required: false },
    idTinhtt: { type: String, required: false },
    idHuyentt: { type: String, required: false },
    idXatt: { type: String, required: false },
    idTinhhn: { type: String, required: false },
    idHuyenhn: { type: String, required: false },
    idXahn: { type: String, required: false },
    dienThoai: { type: String, required: false },
    email: { type: String, required: false },
    idLopHanhChinh: { type: String, required: true },
    idHe: { type: String, required: true },
    idKhoa: { type: String, required: true },
    idKhoaHoc: { type: String, required: true },
    idNganh: { type: String, required: true },
    idTrangThai: { type: String, required: true },
    idLopHienTai: { type: String, required: false },
    idKhoaVien: { type: String, required: false },
    sdtNhanThan: { type: String, required: false },
    ngheNghiepNhanThan: { type: String, required: false },
    ngaySinhNhanThan: { type: String, required: false },
    tenNhanThan: { type: String, required: false },
    moiQuanHe: { type: String, required: false },
    noiONhanThan: { type: String, required: false },
    ngaySinh: { type: Date, required: true },
    idDoiTuongDaoTao: { type: String, required: false },
    ngayQuyetDinhThoiHoc: { type: Date, required: false },
});

export default model<IHoSoNguoiHoc>('HoSoNguoiHoc', schema);
